### ISSUE TITLE
Handle all in one

### ISSUE THREAD

**Issue by temamagic** [tucnak/telebot#158]
I want to handle all in one and work with that. ex, I need to get user info (or chat) from database and do some stuff with other handles

Is there a way to do this?

**Comment by kifirkin** [comment]
You could use general poller like `spamProtected` described here https://github.com/tucnak/telebot#poller and listen to all of the incoming updates

**Comment by kfreiman** [comment]
Telebot is awesome, but actually, it's not clear how to implemet middleware with passing data to `Handle` method, becouse `telebot` almost does not use interfaces. 

`spamProtected` works like filter only. Other middlewares cant recieve data from it.

I tryed use approach from [echo](https://echo.labstack.com/guide/context) for extending Message. But i stucked on absence of interfaces.

**Comment by demget** [comment]
@kfreiman Approach from `echo` is really interesting, which has the right to life.

I was thinking about better handle like so:

```go
func OnStart(c *tb.MessageContext) error {
    return c.Reply("Hello!")
}
```

Using context-related methods is very helpful in error handling. It skips a result and returns single error. It gives an opportunity to handle all errors in one place. Together with context functions, you still can use simple methods with returned result:

```go
func OnStart(c *tb.MessageContext) error {
    msg, err := b.Send(c.Sender, "Hello!")
    if err != nil {
        return err
    }

    // but if you don't need sent message
    return c.Send("Hello!")
}
```

I think something like this is quite real in an experimental or completely new version of the `telebot`!

This issue is also related to #155 and #165.
