### ISSUE TITLE
Ability to set another URL or IP with PORT

### ISSUE THREAD

**Issue by maxim-avramenko** [tucnak/telebot#173]
https://github.com/tucnak/telebot/blob/2adea7c8be7158999ca414230da5c0314d6382ab/api.go#L22

Maybe check environment variable and use it if exist?

expose TELEGRAM_API_URL="http://195.129.111.17:8012"

for use custom route with proxy_path

**Comment by idexter** [comment]
@maxim-avramenko I made a pull request. Maybe it can help. Waiting for @tucnak approvement 😄

**Comment by maxim-avramenko** [comment]
> @maxim-avramenko I made a pull request. Maybe it can help. Waiting for @tucnak approvement

Лэт ми спик фром май харт! Ю ар зэ бёст! Ноу! Форгет ит! Ю ар зэ бёст оф зэ бёст! Ремембер зис! Итс ворк!!!!
Хвала яйцам! Нашлись добрые люди знающие Go Lang и понимающие всю нелепость действий РосКомНадзора. Братан, от души душевно в душу! С меня магарыч!

**Comment by bryanpedini** [comment]
@maxim-avramenko write in damn English bro; no, seriously...
I come here like 2 years later to dig for some code and documentation and my AdBlocker activates russian filters because you didn't have the wish to use 0.1% more brain to talk in english, even tho you clearly know it since you use it in the previous post... oh come on!

English is not my main language too, but here, on GitHub, since everyone can look out code and comments; and most importantly, since this is not a three-people project, confined by the walls of a school or something like that; I too try to use English-only to better undersand, and be understood!

Not a personal or targeted critique, just a general one. But please follow the standards of the internet for a better user experience for everybody else!

**Comment by idexter** [comment]
@bryanpedini He just said: "Thanks" no more no less. 😃

**Comment by bryanpedini** [comment]
> @bryanpedini He just said: "Thanks" no more no less. smiley

Yeah.. thanks for the explaination :smiley:
