### ISSUE TITLE
Add context support for api calls

### ISSUE THREAD

**Issue by mitinarseny** [tucnak/telebot#222]
It would be cool if there is support for passing [`context.Context`](https://golang.org/pkg/context/#Context) in bot api calls like this:
```go
ctx, _ := context.WithTimeout(context.Background(), 10*time.Second)
b, err := tb.NewBot(ctx, &tb.Settings{...})
```
It is useful since often you can not guess from your server logs whether it just freezes or it waits for the bot to get response from `/getMe`.
You can use [`http.NewRequestWithContext`](https://golang.org/pkg/net/http/#NewRequestWithContext) in [api.go](https://github.com/tucnak/telebot/blob/v2/api.go#L29) to do it.

**Comment by stek29** [comment]
I’m not sure that global context is a good idea.
Also, using custom http.Client which adds context to all requests may be enough to achieve global per-bot context.

Adding context to API requests makes more sense, however, it would be a breaking change.

Adding wrappers to keep backward compatibility might help, but it’ll make code bloated and add duplicated code.

**Comment by swithek** [comment]
@demget @tucnak I don't think this issue should be closed. It would be nice to have API methods that accept `context.Context` and handle its cancellation events. This would be especially useful for LongPoller's requests that cannot be cancelled until the timeout is reached (internal use case: LongPoller's request should be cancelled when a stop event is received).

Considering the v3 is currently in development, this is the perfect time to implement this. The changes wouldn't be that complex either:
- `Bot.Raw()` would have to accept `ctx context.Context` as its first parameter and pass it into `http.NewRequestWithContext()` (this func would be used instead of the simple `client.Post()`).
- All the other methods that use `Bot.Raw()` would have to accept a `context.Context` as their first parameters as well.
