### ISSUE TITLE
telebot: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by DongwonTTuna** [tucnak/telebot#332]
```
var poller = &tb.LongPoller{Timeout: 15 * time.Second}
var bp *tb.Bot
var spamProtected = tb.NewMiddlewarePoller(poller, func(upd *tb.Update) bool {	
...
}
bot, err := tb.NewBot(tb.Settings{
		URL: "https://my_address.men/callback",
		Token:  "1113089234:Token______LzMl6WwhxAX75663GGPKKAU",
		Poller: spamProtected,
	})
	if err != nil {
		log.Fatal(err)
		return
	}
```

![스크린샷 2020-11-07 13 28 53](https://user-images.githubusercontent.com/38794795/98431945-3a307100-20fd-11eb-9025-dd70f8c4db91.png)

**Comment by demget** [comment]
Most likely your custom server's response is invalid.

**Comment by danilax86** [comment]
> Most likely your custom server's response is invalid.

Official telegram server actually sends tls handshake info with json data, even if Content-Type header is set to application/json.

In my case, I tried to get file from disk, send it to telegram and receive file id. Telegram sends json data with file id, but json parsing fails because of handshake info :(

Please, reopen
