### ISSUE TITLE
Reserved Telegram characters ().-_ when using Markdown parse_mode.

### ISSUE THREAD

**Issue by arshamalh** [tucnak/telebot#553]
When using Markdown or MarkdownV2, some characters `()_-.` are reserved by Telegram itself and should be escaped unless we get an error, if the case of underline, we don't even get a clear error.

Errors:
```
telegram: Bad Request: can't parse entities: Character '(' is reserved and must be escaped with the preceding '\' (400)
exit status 0xc000013a
```

The worst-case scenario with the underline:
```
telegram: Bad Request: can't parse entities: Can't find end of Italic entity at byte offset 30 (400)
```
And after investigating the results, I realized it's because of underline character.

**Comment by demget** [comment]
You must care about escaping by yourself, it's your responsibility to be sure the message is correct in chosen formatting option. Otherwise, markdown features won't even work. Using HTML is the safest option if you don't want to care about it.

**Comment by eekstunt** [comment]
For anyone still landing here: instead of escaping or switching to HTML, you can skip parse_mode and send plain text + entities. Telegram applies formatting from entities directly (much better approach, more stable)

I ported [telegramify-markdown](https://github.com/sudoskys/telegramify-markdown) (Python, 600+ stars) to Go: [telegramify-markdown-go](https://github.com/eekstunt/telegramify-markdown-go). Use it in my bot daily, no escaping issues since.
