### ISSUE TITLE
How to send contact to user?

### ISSUE THREAD

**Issue by rkakrik** [tucnak/telebot#591]
I tried to send Contact and ContactResult, but with no result. What is the correct way to send a contact?

**Comment by roreng** [comment]
> I tried to send Contact and ContactResult, but with no result. What is the correct way to send a contact?

Unfortunately, telebot does not support sending contacts because the Contact structure does not conform to the Sendable interface and the sendContact API method is not implemented. However, you can implement similar functionality yourself using the Telegram API.

As an example:

```
// SendContact sends phone contacts to the current recipient.
func SendContact(to tele.Recipient, contact tele.Contact) error {
	params := map[string]string{
		"chat_id":      to.Recipient(),
		"phone_number": contact.PhoneNumber,
		"first_name":   contact.FirstName,
	}

	if contact.LastName != "" {
		params["last_name"] = contact.LastName
	}

	_, err := bot.Raw("sendContact", params)
	return err
}
```

By studying [the current documentation](https://core.telegram.org/bots/api#sendcontact), you will be able to use other optional parameters.
