### ISSUE TITLE
How do you tel bot to idle in a channel?

### ISSUE THREAD

**Issue by timogoosen** [tucnak/telebot#80]
I've read over most of the code for this library. How do I tell my bot to join a channel?
Can't seem to figure this out. Thanks. Great library btw!

**Comment by drdaeman** [comment]
*(Just passing by, not related to the project)* I believe you can't. Unless I'm unaware of something, bots cannot initiate new conversations, be it a one-to-one chat or joining a new channel. A human has to invite (=add) bot manually. That is, if the bot is configured to be able to join groups (using `/setjoingroups` with `@botfather`).

**Comment by timogoosen** [comment]
Thanks

**Comment by timogoosen** [comment]
Okay that helped a great deal I was able to add my bot a group thanks to your reply. Btw I meant group and not channel when I wrote this question. (My bad). How do I reply to a message in the group and also how do I access messages sent to a group? I tried a few things from the default examples, but didn't get very far.

**Comment by drdaeman** [comment]
Take a look at the very first example in project's README and experiment around a bit, printing various data, etc. It would help.

To get messages (and see which channels you're in) the official REST API function is [`getUpdates`](https://core.telegram.org/bots/api#getting-updates). This project wraps it as a `chan telebot.Message`, because channels are ideomatic Go. There's a `bot.Listen` in the first example:

    messages := make(chan telebot.Message, 100)
    // This starts a gorutine that calls getUpdates HTTP API periodically
    bot.Listen(messages, 1*time.Second)

Or, there's also `bot.Start(...)` that uses `bot.Messages` channel (you still have to init it with `bot.Messages = make(chan telebot.Message, 100)`). The differences with `bot.Listen` is that doesn't start a new goroutine (but blocks current one) and also handles some extras (`bot.Callbacks` & `bot.Queries`). Check the docs and source code for details.

As for the sending - figure out chat IDs (look them up in the updates you receive) and send messages there, `bot.SendMessage(message.Chat, "text", nil)`. If a message has to be a reply to something, you'll need third argument to be `&SendOptions{ReplyTo: message}`. Or something like that, I've just looked at [the documentation](https://godoc.org/github.com/tucnak/telebot#SendOptions) very briefly, so there could be some typos.

If still unsure, start not with Go, but get familiar with bare HTTP APIs (using curl or just a web browser) and then continue with Go. There are many introductory articles like [this one](https://unnikked.ga/getting-started-with-telegram-bots-9e467d922d69) (not affiliated, just a first link I found in Google)

Hope that helps.

**Comment by timogoosen** [comment]
Thanks this helps. WIll look into it.

**Comment by timogoosen** [comment]
Hey for anyone else wondering about this. By default if you add a bot to a group then it won't be able to access the general messages in the group see: [`Telegram FAQ`](https://telegram.org/faq)
which says: 

> Q: If I add a bot to my group, can it read my messages?
Bots can work in two modes when you add them to groups. By default, bots only see messages that are meant for them. In this case, you‘ll see ’has no access to messages' in the group members list next to the bot.

Some bots need more information to work, so developers may disable privacy mode. In this case, the bot will see all messages sent to the group, and you will see ‘has access to messages’ in the members list next to the bot.

Learn more about privacy mode for bots »

If your group contains very sensitive information, maybe it‘s better to avoid adding bots you don’t trust 100%.

**Comment by tucnak** [comment]
Cheers!
