### ISSUE TITLE
MessageEntity with EntityMention type broken?

### ISSUE THREAD

**Issue by Riketta** [tucnak/telebot#90]
Can't receive User info from MessageEntity instance via such code:
`			for _, v := range message.Entities {
				if v.Type == telebot.EntityMention || v.Type == telebot.EntityTMention { 
					fmt.Println("[Entity]", v)
				}
			}`
Possible output:
> [Entity] {mention 0 8  {0   }}
> [MSG]: From ... in chat #b2: @riketta
> [Entity] {mention 4 8  {0   }}
> [MSG]: From ... in chat #b2: qwe @riketta  aasas

Seems like entity.User contains nothing useful. Sorry if I'm doing smth wrong.

**Comment by tucnak** [comment]
According to Telegram Bot API, `MessageEntity.User` is for users without username only (see https://core.telegram.org/bots/api#messageentity).

For users with username, you can just go and slice it like that: `msg.Text[offset:offset+length]`. It gets trickier for any other mentions though! Since UTF-16 code points may not be 1-byte long, you can't just slice them straight away (strings in Go are immutable []byte and UTF-16 is a variable-length encoding)... I guess we could to introduce a helper function for this very reason.
